// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMSw1nUqLOyJVr3gPAb4GBnYRDJWmG5U',
    appId: '1:830274733310:web:cb46f0599a1d6ac26691af',
    messagingSenderId: '830274733310',
    projectId: 'vender-machine-3ecd6',
    authDomain: 'vender-machine-3ecd6.firebaseapp.com',
    databaseURL: 'https://vender-machine-3ecd6-default-rtdb.firebaseio.com',
    storageBucket: 'vender-machine-3ecd6.appspot.com',
    measurementId: 'G-9SSG43RXWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDhNpG-QoAcQv_TmkItaueKhqAIBqlws',
    appId: '1:830274733310:android:73069fa3f09b11d66691af',
    messagingSenderId: '830274733310',
    projectId: 'vender-machine-3ecd6',
    databaseURL: 'https://vender-machine-3ecd6-default-rtdb.firebaseio.com',
    storageBucket: 'vender-machine-3ecd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhf4d4Wlb09Pfc50nQchhmjTYS37aqnI',
    appId: '1:830274733310:ios:0a56c29678e9427d6691af',
    messagingSenderId: '830274733310',
    projectId: 'vender-machine-3ecd6',
    databaseURL: 'https://vender-machine-3ecd6-default-rtdb.firebaseio.com',
    storageBucket: 'vender-machine-3ecd6.appspot.com',
    androidClientId: '830274733310-rfsou6a9l4nue36vn7j58qk5j13ua735.apps.googleusercontent.com',
    iosClientId: '830274733310-eh7dj1achmivl6gblfprg87vib1u73s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.venderMachine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhf4d4Wlb09Pfc50nQchhmjTYS37aqnI',
    appId: '1:830274733310:ios:0a56c29678e9427d6691af',
    messagingSenderId: '830274733310',
    projectId: 'vender-machine-3ecd6',
    databaseURL: 'https://vender-machine-3ecd6-default-rtdb.firebaseio.com',
    storageBucket: 'vender-machine-3ecd6.appspot.com',
    androidClientId: '830274733310-rfsou6a9l4nue36vn7j58qk5j13ua735.apps.googleusercontent.com',
    iosClientId: '830274733310-eh7dj1achmivl6gblfprg87vib1u73s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.venderMachine',
  );
}
